name: Build Windows Executable

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-full:
    runs-on: windows-latest
    name: Build Full Version (with PyAudio)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python install_deps.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Build executable
      run: |
        python build_exe.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ClassroomListener-Full-Windows
        path: dist/ClassroomListener.exe

  build-simple:
    runs-on: windows-latest
    name: Build Simple Version (Demo)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.13.2
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Build simple executable
      run: |
        python build_simple.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ClassroomListener-Simple-Windows
        path: dist/ClassroomListener-Simple.exe

  create-release:
    needs: [build-full, build-simple]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/ClassroomListener-Full-Windows/ClassroomListener.exe
          artifacts/ClassroomListener-Simple-Windows/ClassroomListener-Simple.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
